name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp25b
        with:
          pdk: ihp

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttihp25b
        with:
          pdk: ihp

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttihp25b
        with:
          pdk: ihp

  viewer:
  needs: gds
  runs-on: ubuntu-24.04
  permissions:
    pages: write
    id-token: write
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Generate Viewer
      uses: TinyTapeout/tt-gds-action/viewer@ttihp25b

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: gh-pages
        name: github-pages  # Must match deploy name

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages

